version: "3"

services:
  writefreely-web:
    container_name: "writefreely-web"
    build:
      context: .

    volumes:
      - ./keys:/var/lib/writefreely/keys/
      - ./data:/var/lib/writefreely/data/
      - ./pages:/usr/share/writefreely/pages
      - ./static:/usr/share/writefreely/static
      - ./templates:/usr/share/writefreely/templates

    ports:
      - "${DOCKER_WRITEFREELY_HOST_PORT:-8080}:8080"

    env_file:
      - .env

    restart: unless-stopped
